dist: trusty

jobs:
    include:
        - stage: build docker image
        script:
            - docker build -t cf-run-task-demo .
        
        - stage: run docker image
        script:
            - docker run cf-run-task-demo foo bar nash
