language: node_js

services:
  - docker

before_install:
- docker build -t cf-run-task-demo .
- docker run cf-run-task-demo test-dotnet-core "./my-task.sh" my-task $CF_USERNAME $CF_PASSWORD $CF_ORG $CF_SPACE

install: skip

script:
    - echo "skipping tests"